AllCops:
  TargetRubyVersion: 2.5.7
  Exclude:
    - 'Gemfile'
Naming/MemoizedInstanceVariableName:
  Enabled: false
Naming/BlockParameterName:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Style/Alias:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/LambdaCall:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/OptionalArguments:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
